### ISSUE TITLE
Existing bridges not found: public_network referencing host device X which does not exist

### ISSUE THREAD

**Issue by jamie01** [vagrant-libvirt/vagrant-libvirt#1624]
**Describe the bug**
Trying to create a public_network that uses an existing bridge. This has worked with earlier versions (last I remember was 0.8 something) but just brought up a fresh environment with 0.10.8 and hit this issue. The bridge definitely does exist and this Vagrantfile is cloned from a previous working one.

The error message appears to have discovered no host interfaces at all given the "referencing one of " ending.

Note that this is a bridge NOT managed by libvirt in any way. That is, the equivalent libvirt xml I would expect is
```
<interface type='bridge'>
  <source bridge='br-mgmt'/>
```

**To Reproduce**
```
    config.vm.network :public_network,
      :dev => "br-mgmt",
      :mode => "bridge",
      :type => "bridge"
```

```
$ ip link show dev br-mgmt
3: br-mgmt: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500
    link/ether ea:2e:5a:ce:b4:cc brd ff:ff:ff:ff:ff:ff
```

```
$ vagrant up
Bringing machine 'node' up with 'libvirt' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Libvirt Provider:
* network configuration 0 for machine node is a public_network referencing host device 'br-mgmt' which does not exist, consider adding ':dev => ....' referencing one of
```

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**:
- Libvirt version: 7.0.0-3
- Vagrant version [output of `vagrant version`]: 2.2.19
- Vagrant flavour [Upstream or Distro]: distro (debian)
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: vagrant-libvirt (0.10.8, global)

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
[vagrant_log.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/9690551/vagrant_log.txt)

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
    config.vm.define "node" do |node|
        node.vm.box = "debian/bullseye64"
    end
    config.vm.network :public_network,
      :dev => "br-mgmt",
      :mode => "bridge",
      :type => "bridge"
end
```

**Comment by jamie01** [comment]
I saw a couple of raised issues and changes in this area over the last few versions so I rolled back to 0.10.0 and that works, just FYI

**Comment by electrofelix** [comment]
Would you be able to run `virsh -c qemu:///system iface-list --all` and provide the output?

I would have expected br-mgmt to show up in the iface-list returned by libvirt, unless perhaps it caches the original information and doesn't refresh when new devices are added, or perhaps the way the API is calling this is not listing inactive ones as well for some reason.

**Comment by jamie01** [comment]
Not much at all, on the surface this libvirt API seems fundamentally broken

```
$ sudo virsh -c qemu:///system iface-list --all
 Name   State    MAC Address
------------------------------------
 lo     active   00:00:00:00:00:00
```

However, the answer might be here: https://askubuntu.com/questions/1186743/libvirt-doesn-t-recognize-the-network-interfaces

The interfaces on this host are configured via systemd-networkd, save for the loopback which is the only entry in `/etc/network/interfaces`. The br-mgmt interface for example is defined by `/etc/systemd/network/mgmt-bridge.netdev`

Perhaps a solution here is to combine the results of the previous method and the libvirt API call into a set, to support all flavours? Granted, libvirt is still at fault here for being unaware of systemd-networkd - haven't found a bug report on this from a quick search.

**Comment by electrofelix** [comment]
That does seem like the best option, though I suspect it might be a case that it is fixed with libvirt upstream but the version in use for the distro release you are using may not be recent enough?

Based on spinning up an ubuntu 20.04 which I thought had switched to systemd-networkd, suggests that the reason it's not been an issue for everyone is that it's working for some distros.
```
vagrant@ubuntu2004:~$ virsh iface-list --all
 Name     State      MAC Address
----------------------------------------
 eth0     active     52:54:00:6b:fc:d6
 lo       inactive   00:00:00:00:00:00
 virbr0   inactive   52:54:00:fc:da:2e

vagrant@ubuntu2004:~$ systemctl status systemd-networkd
● systemd-networkd.service - Network Service
     Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-10-01 18:35:03 UTC; 9min ago
TriggeredBy: ● systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
   Main PID: 377 (systemd-network)
     Status: "Processing requests..."
      Tasks: 1 (limit: 2273)
     Memory: 3.6M
     CGroup: /system.slice/systemd-networkd.service
             └─377 /lib/systemd/systemd-networkd

Oct 01 18:35:06 ubuntu2004.localdomain systemd-networkd[377]: eth0: DHCPv4 address 192.168.122.215/24 via 192.168.122.1
Oct 01 18:43:15 ubuntu2004.localdomain systemd-networkd[377]: rtnl: received neighbor for link '3' we don't know about, ignoring.
Oct 01 18:43:15 ubuntu2004.localdomain systemd-networkd[377]: rtnl: received neighbor for link '3' we don't know about, ignoring.
Oct 01 18:43:15 ubuntu2004.localdomain systemd-networkd[377]: rtnl: received neighbor for link '3' we don't know about, ignoring.
Oct 01 18:43:15 ubuntu2004.localdomain systemd-networkd[377]: rtnl: received neighbor for link '3' we don't know about, ignoring.
Oct 01 18:43:15 ubuntu2004.localdomain systemd-networkd[377]: virbr0-nic: Link UP
Oct 01 18:43:15 ubuntu2004.localdomain systemd-networkd[377]: virbr0-nic: Gained carrier
Oct 01 18:43:15 ubuntu2004.localdomain systemd-networkd[377]: virbr0: Link UP
Oct 01 18:43:15 ubuntu2004.localdomain systemd-networkd[377]: virbr0-nic: Link DOWN
Oct 01 18:43:15 ubuntu2004.localdomain systemd-networkd[377]: virbr0-nic: Lost carrier
```

Still, likely worth using something that will work from distros on longer support cycles.

Can you check if you get useful output from the following:
```
ip -j link show
```

Since there is a possibility of connecting to a remote libvirt server, I can't assume that there will be ruby on the remote, but hopefully can assume that ip will be present, and try to fall back to that if nothing is in the list returned by libvirt.

**Comment by jamie01** [comment]
Yep, `ip -j link show` works just fine and includes everything. I recall `ifconfig` was deprecated a long time ago so I'd be surprised if there were many hosts laying around without iproute2 and it should be safe to use. And if `ip link` failed you could pretty much guarantee that interfaces are using the legacy `/etc/network/interfaces` so the libvirt API should find them (so you could let it fail silently).

Out of interest in your ubuntu 20.0.4 VM, you don't have anything referencing eth0 in `/etc/network/interfaces*` ?

I'm on libivrt `7.0.0-3` which is Debian 11 stable's current version.

**Comment by electrofelix** [comment]
No, nothing appears under /etc/network for eth0 at all.

Based on that version though, I might check ubuntu 21.10 as well, because 20.04 is libvirt 6.0.0 and 22.04 is 7.6.0, bit surprising that 6.0.0 is working and 7.0.0 isn't.

**Comment by electrofelix** [comment]
Interestingly if I spin up a Debian 11 VM and install libvirt in it, I see eth0 listed in addition to the lo
```
vagrant@debian11:~$ virsh -c qemu:///session iface-list
 Name   State    MAC Address
------------------------------------
 eth0   active   52:54:00:5a:a4:ad
 lo     active   00:00:00:00:00:00

vagrant@debian11:~$ virsh version
Compiled against library: libvirt 7.0.0
Using library: libvirt 7.0.0
Using API: QEMU 7.0.0
Running hypervisor: QEMU 5.2.0

vagrant@debian11:~$ cat /etc/issue
Debian GNU/Linux 11 \n \l
```
Have you upgraded through debian releases? As perhaps it has retained the old interface mechanism while libvirt is expecting a newer API, which is why it's not able to list them all.

The reason I was looking at this, is that it looks like I need to make sure the calls at https://github.com/vagrant-libvirt/vagrant-libvirt/blob/28c68d2f99345f0af30de0d9074b23f853fb52d6/lib/vagrant-libvirt/driver.rb#L200-L206

Be converted to one that returns the device names because it's not really practical to return objects wrapping the interfaces given the XML API for libvirt would be difficult to replicate for devices outside of it's control.

**Comment by Jeansen** [comment]
It seems this is still an issue. Running Debian 11, I had to put my interfaces in /etc/network/interfaces. `virsh -c qemu:///session iface-list` or `virsh -c qemu:///system iface-list --all` would only show me the `lo` device until I update the interface file.

Vagrant version: 2.3.4
vagrant-libvirt plugin version: 0.11.2 (but it's the same in earlier versions).
