### ISSUE TITLE
Error: Libvirt has no compute service

### ISSUE THREAD

**Issue by muzammil-iftikhar** [vagrant-libvirt/vagrant-libvirt#1833]
**Describe the bug**
Whenever I run `vagrant up`, I get the error:
```
Bringing machine 'test_machine' up with 'libvirt' provider...
[fog][DEPRECATION] Unable to require fog/libvirt/compute
[fog][DEPRECATION] Falling back to deprecated path fog/compute/libvirt. The preferred file path format has changed from service/provider to provider/service. Please update this service provider to use the preferred format.
[fog][WARNING] Error while loading provider libvirt: cannot load such file -- fog/compute/libvirt
Error while connecting to Libvirt: libvirt has no compute service
```

**To Reproduce**
1. Install Arch Linux
2. Install Vagrant v2.4.1
3. Install ruby v3.3.5
4. Create any vagrantfile
5. Run `vagrant up`

**Expected behavior**
Machine should start

**Screenshots**
![image](https://github.com/user-attachments/assets/e7c20a99-4ec8-44b5-bdf2-67a84de93f28)
![image](https://github.com/user-attachments/assets/80feb598-2d1a-4467-bf5c-6e1aaa537a55)

**Versions (please complete the following information):**:
- Libvirt version: 10.9.0-1
- Vagrant version [output of `vagrant version`]: 2.4.1
- Vagrant flavour [Upstream or Distro]: Arch
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
```
fog-libvirt (0.12.2, global)
pkg-config (1.5.7, global)
vagrant-libvirt (0.12.3.pre.18, global)
  - Version Constraint: 0.12.3.pre.18
vagrant-mutate (1.2.0, global)
vagrant-scp (0.5.9, global)
vagrant-vbguest (0.32.0, global)
```

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
[vagrant.log](https://github.com/user-attachments/files/17652760/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.box_version = "4.3.12"
end
```

**Comment by SakibFarhad** [comment]
Facing the same issue, can confirm.

**Comment by finnvyrn** [comment]
Hello! I'm facing the same issue too. Did you solve them?

Linux 6.12.1-arch1-1
vagrant 2.4.2-1

**Comment by muzammil-iftikhar** [comment]
@finnvyrn  .. no still waiting for a solution from devs

**Comment by TheJasonPlayz** [comment]
I also have the same issue @finnvyrn

**Comment by roccr** [comment]
Having the same issue

Kernel: 6.12.4-arch1-1
Vagrant: 2.4.3
vagrant plugin list: vagrant-libvirt (0.12.2, global)

**Comment by robertojrojas** [comment]
Just ran into the same issue:
```
Kernel: 6.6.65-1-lts (Arch Linux)
Vagrant: 2.4.3
Vagrant plugin list: 
vagrant-libvirt (0.12.2, global)

Ruby: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]

Gems Installed by plugin:
xml-simple-1.1.9.gem
racc-1.8.1.gem
nokogiri-1.17.2-x86_64-linux.gem
ruby-libvirt-0.8.4.gem
formatador-1.1.0.gem
fog-core-2.6.0.gem
fog-xml-0.1.4.gem
fog-json-1.2.0.gem
fog-libvirt-0.13.1.gem
diffy-3.4.3.gem
vagrant-libvirt-0.12.2.gem

```
A bit more information about how I got here.
I tried to install the lastest plugin vesion using:

```
$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies json (= 2.7.1) and json (= 2.9.0)
  Activated json-2.9.0
  which does not match conflicting dependency (= 2.7.1)

  Conflicting dependency chains:
    json (= 2.9.0), 2.9.0 activated

  versus:
    json (= 2.7.1)

  Gems matching json (= 2.7.1):
    json-2.7.1
```
So I followed the recommendations from the [Arch Linux Vagrant](https://wiki.archlinux.org/title/Vagrant) docs of using:

**export VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1**

```
$ export VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1
$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching xml-simple-1.1.9.gem
Fetching racc-1.8.1.gem
Building native extensions. This could take a while...
Fetching nokogiri-1.17.2-x86_64-linux.gem
Fetching ruby-libvirt-0.8.4.gem
Building native extensions. This could take a while...
Fetching formatador-1.1.0.gem
Fetching fog-core-2.6.0.gem
Fetching fog-xml-0.1.4.gem
Fetching fog-json-1.2.0.gem
Fetching fog-libvirt-0.13.1.gem
Fetching diffy-3.4.3.gem
Fetching vagrant-libvirt-0.12.2.gem
Installed the plugin 'vagrant-libvirt (0.12.2)'!
```

I created a sample Vagrantfile to test it:
```
$ vagrant init generic/ubuntu2004 --box-version 4.3.12
```
and then tried to launch the VM with VAGRANT LOG:
```
$ VAGRANT_LOG=info vagrant up --provider=libvirt

WARN box_check_outdated: Not checking for update, no box
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x000072122b3e4ec8>
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x000072122a5f5358>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::IsCreated:0x000072122a1e68e8>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::IsCreated:0x000072122a1e68e8>
 INFO driver: Connecting to Libvirt (qemu:///system) ...
[fog][DEPRECATION] Unable to require fog/libvirt/compute
[fog][DEPRECATION] Falling back to deprecated path fog/compute/libvirt. The preferred file path format has changed from service/provider to provider/service. Please update this service provider to use the preferred format.
[fog][WARNING] Error while loading provider libvirt: cannot load such file -- fog/compute/libvirt
ERROR warden: Error occurred: Error while connecting to Libvirt: libvirt has no compute service
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000072122b3e4ec8>
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-b776aa39fedc43098ca5a6b6ae7b2a6d
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x000072122a551640>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::ProviderLibvirt::Errors::FogLibvirtConnectionError: Error while connecting to Libvirt: libvirt has no compute service>
ERROR vagrant: Error while connecting to Libvirt: libvirt has no compute service
ERROR vagrant: /home/rrojas/.vagrant.d/gems/3.3.5/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/driver.rb:51:in `rescue in connection'
/home/rrojas/.vagrant.d/gems/3.3.5/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/driver.rb:48:in `connection'
/home/rrojas/.vagrant.d/gems/3.3.5/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/create_networks.rb:28:in `initialize'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:111:in `new'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:111:in `finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:24:in `block in initialize'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:24:in `map'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:24:in `initialize'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/builder.rb:223:in `new'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/builder.rb:223:in `to_app'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/builtin/call.rb:55:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/builtin/box_check_outdated.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/builtin/config_validate.rb:28:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/warden.rb:38:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/builder.rb:183:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/runner.rb:104:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/util/busy.rb:22:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/action/runner.rb:104:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/machine.rb:246:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/machine.rb:215:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/environment.rb:649:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/machine.rb:201:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/machine.rb:201:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-2.4.3/lib/vagrant/batch_action.rb:88:in `block (2 levels) in run'
 INFO interface: error: Error while connecting to Libvirt: libvirt has no compute service
Error while connecting to Libvirt: libvirt has no compute service
 INFO interface: Machine: error-exit ["VagrantPlugins::ProviderLibvirt::Errors::FogLibvirtConnectionError", "Error while connecting to Libvirt: libvirt has no compute service"]

```

**Comment by robertojrojas** [comment]
Yet another work-around that helped me. 
It's a simple shell script with some instructions.
 https://github.com/robertojrojas/vagrant-libvirt/blob/vagrant-v243/tools/vagrant_ibvirt.sh

I hope it helps!

cc:  Thank you @emilio507  for your help!

**Comment by muzammil-iftikhar** [comment]
Thanks @robertojrojas .. your suggestion actually solved half the problem for me. It fixed my 'no compute' error and then gave me 'erb' error. Which was then fixed by this comment:
https://github.com/fog/fog-libvirt/issues/159#issuecomment-2560372220

Credits: @robertojrojas [@Artideusz](https://github.com/Artideusz)

**Comment by ekohl** [comment]
I just released fog-libvirt 0.13.2 which drops the require of `erb`. Please verify if you can still reproduce the issue.

**Comment by RiedleroD** [comment]
this started happening to me today after upgrading my system. the fix was just manually installing fog-libvirt. No other workarounds needed. thanks @ekohl !

**Comment by Sidicer** [comment]
Manually installing `fog-libvirt 0.13.2` does not solve `Error while connecting to Libvirt: libvirt has no compute service` issue.

```sh
❯ vagrant up
Bringing machine 'freebsdvm' up with 'libvirt' provider...
[fog][DEPRECATION] Unable to require fog/libvirt/compute
[fog][DEPRECATION] Falling back to deprecated path fog/compute/libvirt. The preferred file path format has changed from service/provider to provider/service. Please update this service provider to use the preferred format.
[fog][WARNING] Error while loading provider libvirt: cannot load such file -- fog/compute/libvirt
Error while connecting to Libvirt: libvirt has no compute service
```
```sh
❯ sudo gem install fog-libvirt                                                          
WARNING:  You don\'t have /root/.local/share/gem/ruby/3.3.0/bin in your PATH,
	 gem executables will not run.
Successfully installed fog-libvirt-0.13.2
1 gem installed
```
```sh
❯ vagrant up
Bringing machine 'freebsdvm' up with 'libvirt' provider...
[fog][DEPRECATION] Unable to require fog/libvirt/compute
[fog][DEPRECATION] Falling back to deprecated path fog/compute/libvirt. The preferred file path format has changed from service/provider to provider/service. Please update this service provider to use the preferred format.
[fog][WARNING] Error while loading provider libvirt: cannot load such file -- fog/compute/libvirt
Error while connecting to Libvirt: libvirt has no compute service
```

**Comment by RiedleroD** [comment]
@Sidicer I believe the warning you got is relevant. Try instead using `vagrant plugin install fog-libvirt` in the same directory you'll run `vagrant up` in
