### ISSUE TITLE
Domain creation fails at save with "unknown procedure: 350"

### ISSUE THREAD

**Issue by aetherith** [vagrant-libvirt/vagrant-libvirt#716]
### Steps to reproduce
1. Create Vagrantfile to reference remote KVM server.
2. Run `vagrant up sol --provider=libvirt`

### Expected behaviour
The domain should be created and come online.

### Actual behaviour
The process crashes with an error creating the domain, citing an unknown procedure. I am able to connect to the remote server with `vagrant status` but neither the status or `virsh# list --all` show a created domain.

### System configuration
**OS/Distro version:**: Arch Linux connecting to Debian 8.6 over SSH with keyfile.

**Libvirt version:**
```
`--> pacman -Q libvirt
libvirt 2.4.0-2
```

```
$  apt list --installed | grep libvirt

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

libvirt-bin/stable,stable,now 1.2.9-9+deb8u3 amd64 [installed]
libvirt-clients/stable,stable,now 1.2.9-9+deb8u3 amd64 [installed,automatic]
libvirt-daemon/stable,stable,now 1.2.9-9+deb8u3 amd64 [installed,automatic]
libvirt-daemon-system/stable,stable,now 1.2.9-9+deb8u3 amd64 [installed,automatic]
libvirt0/stable,stable,now 1.2.9-9+deb8u3 amd64 [installed,automatic]
python-libvirt/stable,now 1.2.9-1 amd64 [installed,automatic]
```

**Output of `vagrant version; vagrant plugin list`:**
```
`--> vagrant version; vagrant plugin list
Installed Version: 1.9.1
Latest Version: 1.9.1

You're running an up-to-date version of Vagrant!
vagrant-libvirt (0.0.36)
```

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
`--> VAGRANT_LOG=debug vagrant up sol --provider=libvirt
 INFO global: Vagrant version: 1.9.1
 INFO global: Ruby version: 2.2.5
 INFO global: RubyGems version: 2.4.5.1
 INFO global: VAGRANT_LOG="debug"
 INFO global: VAGRANT_OLD_ENV_OLDPWD="/home/aetherith"
 INFO global: VAGRANT_OLD_ENV_EDITOR="vim"
 INFO global: VAGRANT_OLD_ENV_USER="aetherith"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_OLD_ENV_SSH_TTY="/dev/pts/1"
 INFO global: VAGRANT_OLD_ENV_XDG_RUNTIME_DIR="/run/user/1000"
 INFO global: VAGRANT_OLD_ENV_LD_LIBRARY_PATH="/home/aetherith/GNUstep/Library/Libraries:/usr/lib"
 INFO global: VAGRANT_OLD_ENV_HG="/usr/bin/hg"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/embedded"
 INFO global: VAGRANT_OLD_ENV_HOME="/home/aetherith"
 INFO global: VAGRANT_OLD_ENV_XDG_SESSION_ID="c6"
 INFO global: VAGRANT_OLD_ENV_PWD="/home/aetherith/Projects/HomeLab"
 INFO global: VAGRANT_OLD_ENV_GUILE_LOAD_PATH="/home/aetherith/GNUstep/Library/Libraries/Guile:/usr/lib/GNUstep/Libraries/Guile"
 INFO global: VAGRANT_OLD_ENV_PATH="/usr/local/sbin:/home/aetherith/GNUstep/Tools:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/aetherith/.bin:/home/aetherith/.gem/ruby/2.3.0/bin:/usr/local/Cellar/php55/5.5.29/bin:/home/aetherith/.composer/vendor/bin"
 INFO global: VAGRANT_OLD_ENV_SHELL="/usr/bin/zsh"
 INFO global: VAGRANT_OLD_ENV_GNUSTEP_MAKEFILES="/usr/share/GNUstep/Makefiles"
 INFO global: VAGRANT_OLD_ENV_INFOPATH="/usr/share/info::/home/aetherith/GNUstep/Library/Documentation/info:"
 INFO global: VAGRANT_OLD_ENV_ANDROID_HOME="/opt/android-sdk"
 INFO global: VAGRANT_OLD_ENV_MOZ_PLUGIN_PATH="/usr/lib/mozilla/plugins"
 INFO global: VAGRANT_OLD_ENV__="/usr/bin/vagrant"
 INFO global: VAGRANT_OLD_ENV_SSH_CLIENT="207.87.220.194 22222 22"
 INFO global: VAGRANT_OLD_ENV_CLASSPATH="/home/aetherith/GNUstep/Library/Libraries/Java:/usr/lib/GNUstep/Libraries/Java"
 INFO global: VAGRANT_OLD_ENV_ANT_HOME="/usr/share/apache-ant"
 INFO global: VAGRANT_OLD_ENV_SSH_AUTH_SOCK="/tmp/ssh-YkrCwTSCOnk9/agent.2370"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant"
 INFO global: VAGRANT_OLD_ENV_MAIL="/var/spool/mail/aetherith"
 INFO global: VAGRANT_OLD_ENV_SSH_CONNECTION="207.87.220.194 22222 192.168.1.90 22"
 INFO global: VAGRANT_OLD_ENV_DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
 INFO global: VAGRANT_OLD_ENV_LOGNAME="aetherith"
 INFO global: VAGRANT_OLD_ENV_TERM="xterm-256color"
 INFO global: VAGRANT_OLD_ENV_SHLVL="1"
 INFO global: VAGRANT_OLD_ENV_LANG="en_US.UTF-8"
 INFO global: VAGRANT_OLD_ENV_SSH_AGENT_PID="2371"
 INFO global: VAGRANT_OLD_ENV_VAGRANT_LOG="debug"
 INFO global: Plugins:
 INFO global:   - vagrant-libvirt = [installed: 0.0.36 constraint: > 0]
DEBUG bundler: Current generated plugin dependency list: [<Gem::Dependency type=:runtime name="vagrant-libvirt" requirements="> 0">]
DEBUG bundler: Generating new builtin set instance.
DEBUG bundler: Generating new plugin set instance. Skip gems - []
DEBUG bundler: Activating solution set: ["vagrant-libvirt-0.0.36", "nokogiri-1.6.7.1", "fog-libvirt-0.3.0", "mini_portile2-2.0.0", "json-1.8.1", "ruby-libvirt-0.7.0", "fog-xml-0.1.2", "fog-json-1.0.2", "fog-core-1.43.0", "multi_json-1.12.1", "formatador-0.2.5", "excon-0.54.0", "builder-3.2.2"]
DEBUG bundler: Activating gem vagrant-libvirt-0.0.36
DEBUG bundler: Failed to load solution set. Retrying with reverse order.
DEBUG bundler: Activating solution set: ["builder-3.2.2", "excon-0.54.0", "formatador-0.2.5", "multi_json-1.12.1", "fog-core-1.43.0", "fog-json-1.0.2", "fog-xml-0.1.2", "ruby-libvirt-0.7.0", "json-1.8.1", "mini_portile2-2.0.0", "fog-libvirt-0.3.0", "nokogiri-1.6.7.1", "vagrant-libvirt-0.0.36"]
DEBUG bundler: Activating gem excon-0.54.0
DEBUG bundler: Activating gem formatador-0.2.5
DEBUG bundler: Activating gem fog-core-1.43.0
DEBUG bundler: Activating gem fog-json-1.0.2
DEBUG bundler: Activating gem fog-xml-0.1.2
DEBUG bundler: Activating gem ruby-libvirt-0.7.0
DEBUG bundler: Activating gem fog-libvirt-0.3.0
DEBUG bundler: Activating gem vagrant-libvirt-0.0.36
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/kernel_v1/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/pushes/local-exec/plugin.rb
 INFO manager: Registered plugin: local-exec
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/pushes/noop/plugin.rb
 INFO manager: Registered plugin: noop
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/pushes/heroku/plugin.rb
 INFO manager: Registered plugin: heroku
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/pushes/ftp/plugin.rb
 INFO manager: Registered plugin: ftp
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/pushes/atlas/plugin.rb
 INFO manager: Registered plugin: atlas
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/kernel_v2/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/hosts/linux/plugin.rb
 INFO manager: Registered plugin: Linux host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/hosts/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/hosts/arch/plugin.rb
 INFO manager: Registered plugin: Arch host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/hosts/null/plugin.rb
 INFO manager: Registered plugin: null host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/hosts/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/hosts/windows/plugin.rb
 INFO manager: Registered plugin: Windows host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/hosts/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/hosts/suse/plugin.rb
 INFO manager: Registered plugin: SUSE host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/hosts/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/hosts/bsd/plugin.rb
 INFO manager: Registered plugin: BSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/hosts/darwin/plugin.rb
 INFO manager: Registered plugin: Mac OS X host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/netbsd/plugin.rb
 INFO manager: Registered plugin: NetBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/linux/plugin.rb
 INFO manager: Registered plugin: Linux guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/omnios/plugin.rb
 INFO manager: Registered plugin: OmniOS guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/mint/plugin.rb
 INFO manager: Registered plugin: Mint guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/arch/plugin.rb
 INFO manager: Registered plugin: Arch guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/amazon/plugin.rb
 INFO manager: Registered plugin: Amazon Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/debian/plugin.rb
 INFO manager: Registered plugin: Debian guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/solaris11/plugin.rb
 INFO manager: Registered plugin: Solaris 11 guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/tinycore/plugin.rb
 INFO manager: Registered plugin: TinyCore Linux guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/photon/plugin.rb
 INFO manager: Registered plugin: VMware Photon guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/windows/plugin.rb
 INFO manager: Registered plugin: Windows guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/trisquel/plugin.rb
 INFO manager: Registered plugin: Trisquel guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/funtoo/plugin.rb
 INFO manager: Registered plugin: Funtoo guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/dragonflybsd/plugin.rb
 INFO manager: Registered plugin: DragonFly BSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/openbsd/plugin.rb
 INFO manager: Registered plugin: OpenBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/smartos/plugin.rb
 INFO manager: Registered plugin: SmartOS guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/esxi/plugin.rb
 INFO manager: Registered plugin: ESXi guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/pld/plugin.rb
 INFO manager: Registered plugin: PLD Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/coreos/plugin.rb
 INFO manager: Registered plugin: CoreOS guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/suse/plugin.rb
 INFO manager: Registered plugin: SUSE guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/solaris/plugin.rb
 INFO manager: Registered plugin: Solaris guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/ubuntu/plugin.rb
 INFO manager: Registered plugin: Ubuntu guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/bsd/plugin.rb
 INFO manager: Registered plugin: BSD-based guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/darwin/plugin.rb
 INFO manager: Registered plugin: Darwin guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/nixos/plugin.rb
 INFO manager: Registered plugin: NixOS guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/atomic/plugin.rb
 INFO manager: Registered plugin: Atomic Host guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/guests/fedora/plugin.rb
 INFO manager: Registered plugin: Fedora guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/docker/plugin.rb
 INFO manager: Registered plugin: docker-provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/hyperv/plugin.rb
 INFO manager: Registered plugin: Hyper-V provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/virtualbox/plugin.rb
 INFO manager: Registered plugin: VirtualBox provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/communicators/winrm/plugin.rb
 INFO manager: Registered plugin: winrm communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/communicators/ssh/plugin.rb
 INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/plugin.rb
 INFO manager: Registered plugin: plugin command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/provider/plugin.rb
 INFO manager: Registered plugin: provider command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/version/plugin.rb
 INFO manager: Registered plugin: version command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/halt/plugin.rb
 INFO manager: Registered plugin: halt command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/provision/plugin.rb
 INFO manager: Registered plugin: provision command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/destroy/plugin.rb
 INFO manager: Registered plugin: destroy command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/box/plugin.rb
 INFO manager: Registered plugin: box command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/cap/plugin.rb
 INFO manager: Registered plugin: cap command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/powershell/plugin.rb
 INFO manager: Registered plugin: powershell command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/suspend/plugin.rb
 INFO manager: Registered plugin: suspend command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/port/plugin.rb
 INFO manager: Registered plugin: port command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/ssh_config/plugin.rb
 INFO manager: Registered plugin: ssh-config command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/ssh/plugin.rb
 INFO manager: Registered plugin: ssh command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/help/plugin.rb
 INFO manager: Registered plugin: help command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/global-status/plugin.rb
 INFO manager: Registered plugin: global-status command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/init/plugin.rb
 INFO manager: Registered plugin: init command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/reload/plugin.rb
 INFO manager: Registered plugin: reload command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/status/plugin.rb
 INFO manager: Registered plugin: status command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/list-commands/plugin.rb
 INFO manager: Registered plugin: list-commands command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/package/plugin.rb
 INFO manager: Registered plugin: package command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/push/plugin.rb
 INFO manager: Registered plugin: push command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/up/plugin.rb
 INFO manager: Registered plugin: up command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/resume/plugin.rb
 INFO manager: Registered plugin: resume command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/login/plugin.rb
 INFO manager: Registered plugin: vagrant-login
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/rdp/plugin.rb
 INFO manager: Registered plugin: rdp command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/snapshot/plugin.rb
 INFO manager: Registered plugin: snapshot command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/provisioners/ansible/plugin.rb
 INFO manager: Registered plugin: ansible
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/provisioners/cfengine/plugin.rb
 INFO manager: Registered plugin: CFEngine Provisioner
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/provisioners/shell/plugin.rb
 INFO manager: Registered plugin: shell
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/provisioners/file/plugin.rb
 INFO manager: Registered plugin: file
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/provisioners/chef/plugin.rb
 INFO manager: Registered plugin: chef
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/provisioners/docker/plugin.rb
 INFO manager: Registered plugin: docker
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/provisioners/puppet/plugin.rb
 INFO manager: Registered plugin: puppet
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/provisioners/salt/plugin.rb
 INFO manager: Registered plugin: salt
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/synced_folders/smb/plugin.rb
 INFO manager: Registered plugin: SMB synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/synced_folders/nfs/plugin.rb
 INFO manager: Registered plugin: NFS synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/synced_folders/rsync/plugin.rb
 INFO manager: Registered plugin: RSync synced folders
 INFO global: Loading plugins!
DEBUG global: Loading plugin `vagrant-libvirt` with default require: `vagrant-libvirt`
 INFO manager: Registered plugin: libvirt
DEBUG global: Successfully loaded plugin `vagrant-libvirt`.
 INFO vagrant: `vagrant` invoked: ["up", "sol", "--provider=libvirt"]
DEBUG vagrant: Creating Vagrant environment
 INFO environment: Environment initialized (#<Vagrant::Environment:0x00000002263980>)
 INFO environment:   - cwd: /home/aetherith/Projects/HomeLab
 INFO environment: Home path: /home/aetherith/.vagrant.d
DEBUG environment: Effective local data path: /home/aetherith/Projects/HomeLab/.vagrant
 INFO environment: Local data path: /home/aetherith/Projects/HomeLab/.vagrant
DEBUG environment: Creating: /home/aetherith/Projects/HomeLab/.vagrant
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Builder:0x000000021a9710>
 INFO environment: Running hook: environment_load
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x00000001f497b8>
 INFO cli: CLI: [] "up" ["sol", "--provider=libvirt"]
DEBUG cli: Invoking command class: VagrantPlugins::CommandUp::Command ["sol", "--provider=libvirt"]
DEBUG command: 'Up' each target VM...
DEBUG command: Getting target VMs for command. Arguments:
DEBUG command:  -- names: ["sol"]
DEBUG command:  -- options: nil
DEBUG command: Finding machine that match name: sol
 INFO loader: Set :root = ["#<Pathname:/home/aetherith/Projects/HomeLab/Vagrantfile>"]
DEBUG loader: Populating proc cache for #<Pathname:/home/aetherith/Projects/HomeLab/Vagrantfile>
DEBUG loader: Load procs for pathname: /home/aetherith/Projects/HomeLab/Vagrantfile
 INFO loader: Loading configuration in order: [:home, :root]
DEBUG loader: Loading from: root (evaluating)
DEBUG provisioner: Provisioner defined:
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO loader: Set "13874920_machine_sol" = ["[\"2\", #<Proc:0x00000002131940@/home/aetherith/Projects/HomeLab/Vagrantfile:20>]"]
DEBUG loader: Populating proc cache for ["2", #<Proc:0x00000002131940@/home/aetherith/Projects/HomeLab/Vagrantfile:20>]
 INFO loader: Loading configuration in order: [:home, :root, "13874920_machine_sol"]
DEBUG loader: Loading from: root (cache)
DEBUG loader: Loading from: 13874920_machine_sol (evaluating)
DEBUG provisioner: Provisioner defined:
DEBUG provisioner: Provisioner defined:
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO environment: Getting machine: sol (libvirt)
 INFO environment: Uncached load of machine.
 INFO loader: Set "13874920_machine_sol" = ["[\"2\", #<Proc:0x00000002131940@/home/aetherith/Projects/HomeLab/Vagrantfile:20>]"]
 INFO loader: Loading configuration in order: [:home, :root, "13874920_machine_sol"]
DEBUG loader: Loading from: root (cache)
DEBUG loader: Loading from: 13874920_machine_sol (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO box_collection: Box found: debian/jessie64 (libvirt)
 INFO environment: Running hook: authenticate_box_url
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/aetherith/Projects/HomeLab>]
DEBUG host: Trying: redhat
DEBUG host: Trying: arch
 INFO host: Detected: arch!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 3 hooks defined.
 INFO runner: Running action: authenticate_box_url #<Vagrant::Action::Builder:0x000000015d1320>
 INFO warden: Calling IN action: #<VagrantPlugins::LoginCommand::AddAuthentication:0x00000002b323b8>
DEBUG client: No authentication token in environment or /home/aetherith/.vagrant.d/data/vagrant_login_token
 INFO warden: Calling OUT action: #<VagrantPlugins::LoginCommand::AddAuthentication:0x00000002b323b8>
 INFO loader: Set :"16085400_debian/jessie64_libvirt" = ["#<Pathname:/home/aetherith/.vagrant.d/boxes/debian-VAGRANTSLASH-jessie64/8.5.0/libvirt/Vagrantfile>"]
DEBUG loader: Populating proc cache for #<Pathname:/home/aetherith/.vagrant.d/boxes/debian-VAGRANTSLASH-jessie64/8.5.0/libvirt/Vagrantfile>
DEBUG loader: Load procs for pathname: /home/aetherith/.vagrant.d/boxes/debian-VAGRANTSLASH-jessie64/8.5.0/libvirt/Vagrantfile
 INFO loader: Loading configuration in order: [:"16085400_debian/jessie64_libvirt", :home, :root, "13874920_machine_sol"]
DEBUG loader: Loading from: 16085400_debian/jessie64_libvirt (evaluating)
DEBUG loader: Loading from: root (cache)
DEBUG loader: Loading from: 13874920_machine_sol (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO machine: Initializing machine: sol
 INFO machine:   - Provider: VagrantPlugins::ProviderLibvirt::Provider
 INFO machine:   - Box: #<Vagrant::Box:0x00000002a73940>
 INFO machine:   - Data dir: /home/aetherith/Projects/HomeLab/.vagrant/machines/sol/libvirt
 INFO machine: New machine ID: nil
 INFO interface: Machine: metadata ["provider", :libvirt, {:target=>:sol}]
 INFO command: With machine: sol (#<VagrantPlugins::ProviderLibvirt::Provider:0x00000002dbd4e8 @machine=#<Vagrant::Machine: sol (VagrantPlugins::ProviderLibvirt::Provider)>, @cap_logger=#<Log4r::Logger:0x00000002dbce58 @fullname="vagrant::capability_host::vagrantplugins::providerlibvirt::provider", @outputters=[], @additive=true, @name="provider", @path="vagrant::capability_host::vagrantplugins::providerlibvirt", @parent=#<Log4r::Logger:0x0000000164f4c8 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x000000015fba80 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x000000015fb9e0>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x000000015ee5d8 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x0000000164f360 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @cap_host_chain=[[:libvirt, #<#<Class:0x00000002dbd470>:0x00000002da3a98>]], @cap_args=[#<Vagrant::Machine: sol (VagrantPlugins::ProviderLibvirt::Provider)>], @cap_caps={:docker=>#<Vagrant::Registry:0x00000002dbd2b8 @items={:public_address=>#<Proc:0x00000001ecac88@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/docker/plugin.rb:60>, :proxy_machine=>#<Proc:0x00000001ecab48@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/docker/plugin.rb:65>}, @results_cache={}>, :hyperv=>#<Vagrant::Registry:0x00000002dbd218 @items={:public_address=>#<Proc:0x00000001f81b40@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/hyperv/plugin.rb:25>, :snapshot_list=>#<Proc:0x00000001f81ac8@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/hyperv/plugin.rb:30>}, @results_cache={}>, :virtualbox=>#<Vagrant::Registry:0x00000002dbd150 @items={:forwarded_ports=>#<Proc:0x00000001ea5780@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/virtualbox/plugin.rb:27>, :nic_mac_addresses=>#<Proc:0x00000001ea56e0@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/virtualbox/plugin.rb:32>, :public_address=>#<Proc:0x00000001ea56b8@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/virtualbox/plugin.rb:37>, :snapshot_list=>#<Proc:0x00000001ea5690@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/virtualbox/plugin.rb:42>}, @results_cache={}>, :libvirt=>#<Vagrant::Registry:0x00000002dbd088 @items={:nic_mac_addresses=>#<Proc:0x00000001af1238@/home/aetherith/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/plugin.rb:38>}, @results_cache={}>}>)
DEBUG host: Searching for cap: provider_install_libvirt
DEBUG host: Checking in: arch
DEBUG host: Checking in: linux
DEBUG command: Getting target VMs for command. Arguments:
DEBUG command:  -- names: ["sol"]
DEBUG command:  -- options: {:provider=>"libvirt"}
DEBUG command: Finding machine that match name: sol
 INFO environment: Getting machine: sol (libvirt)
 INFO environment: Returning cached machine: sol (libvirt)
 INFO command: With machine: sol (#<VagrantPlugins::ProviderLibvirt::Provider:0x00000002dbd4e8 @machine=#<Vagrant::Machine: sol (VagrantPlugins::ProviderLibvirt::Provider)>, @cap_logger=#<Log4r::Logger:0x00000002dbce58 @fullname="vagrant::capability_host::vagrantplugins::providerlibvirt::provider", @outputters=[], @additive=true, @name="provider", @path="vagrant::capability_host::vagrantplugins::providerlibvirt", @parent=#<Log4r::Logger:0x0000000164f4c8 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x000000015fba80 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x000000015fb9e0>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x000000015ee5d8 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x0000000164f360 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @cap_host_chain=[[:libvirt, #<#<Class:0x00000002dbd470>:0x00000002da3a98>]], @cap_args=[#<Vagrant::Machine: sol (VagrantPlugins::ProviderLibvirt::Provider)>], @cap_caps={:docker=>#<Vagrant::Registry:0x00000002dbd2b8 @items={:public_address=>#<Proc:0x00000001ecac88@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/docker/plugin.rb:60>, :proxy_machine=>#<Proc:0x00000001ecab48@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/docker/plugin.rb:65>}, @results_cache={}>, :hyperv=>#<Vagrant::Registry:0x00000002dbd218 @items={:public_address=>#<Proc:0x00000001f81b40@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/hyperv/plugin.rb:25>, :snapshot_list=>#<Proc:0x00000001f81ac8@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/hyperv/plugin.rb:30>}, @results_cache={}>, :virtualbox=>#<Vagrant::Registry:0x00000002dbd150 @items={:forwarded_ports=>#<Proc:0x00000001ea5780@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/virtualbox/plugin.rb:27>, :nic_mac_addresses=>#<Proc:0x00000001ea56e0@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/virtualbox/plugin.rb:32>, :public_address=>#<Proc:0x00000001ea56b8@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/virtualbox/plugin.rb:37>, :snapshot_list=>#<Proc:0x00000001ea5690@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/virtualbox/plugin.rb:42>}, @results_cache={}>, :libvirt=>#<Vagrant::Registry:0x00000002dbd088 @items={:nic_mac_addresses=>#<Proc:0x00000001af1238@/home/aetherith/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/plugin.rb:38>}, @results_cache={}>}>)
 INFO interface: info: Bringing machine 'sol' up with 'libvirt' provider...
Bringing machine 'sol' up with 'libvirt' provider...
 INFO batch_action: Enabling parallelization by default.
 INFO batch_action: Disabling parallelization because only executing one action
 INFO batch_action: Batch action will parallelize: false
 INFO batch_action: Starting action: #<Vagrant::Machine:0x00000002e009a0> up {:destroy_on_error=>true, :install_provider=>true, :parallel=>true, :provision_ignore_sentinel=>false, :provision_types=>nil, :provider=>"libvirt"}
 INFO machine: Calling action: up on provider Libvirt (new)
DEBUG environment: Attempting to acquire process-lock: machine-action-c518416c6a67f5125863488caa8cc9e1
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-c518416c6a67f5125863488caa8cc9e1
 INFO interface: Machine: action ["up", "start", {:target=>:sol}]
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x00000002c2e7a8>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000002c058f8>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x00000002c058d0>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x00000002b70438>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::IsCreated:0x00000002b685a8>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::IsCreated:0x00000002b685a8>
Ignoring ruby-libvirt-0.7.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.7.0
 INFO driver: Connecting to Libvirt (qemu+ssh://aetherith@ymir.asgard.aetherith.net/system?no_verify=1&keyfile=/home/aetherith/.ssh/id_rsa) ...
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Warden:0x00000002e5aba8>
 INFO warden: Calling IN action: #<Proc:0x00000002dd47d8@/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::SetNameOfDomain:0x00000002e5aae0>
 INFO set_name_of_domain: Looking for domain HomeLab_sol through list []
 INFO set_name_of_domain: Looking for domain HomeLab_sol
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::HandleStoragePool:0x00000002e42b48>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::HandleBox:0x00000002e162c8>
 INFO handle_box: Machine already has box. HandleBox will not run.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::HandleBoxImage:0x00000002df5140>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateDomainVolume:0x00000002dd3b08>
 INFO interface: info: Creating image (snapshot of base box volume).
 INFO interface: info: ==> sol: Creating image (snapshot of base box volume).
==> sol: Creating image (snapshot of base box volume).
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateDomain:0x00000002db3970>
 INFO interface: info: Creating domain with the following settings...
 INFO interface: info: ==> sol: Creating domain with the following settings...
==> sol: Creating domain with the following settings...
 INFO interface: info:  -- Name:              HomeLab_sol
 INFO interface: info: ==> sol:  -- Name:              HomeLab_sol
==> sol:  -- Name:              HomeLab_sol
 INFO interface: info:  -- Domain type:       kvm
 INFO interface: info: ==> sol:  -- Domain type:       kvm
==> sol:  -- Domain type:       kvm
 INFO interface: info:  -- Cpus:              2
 INFO interface: info: ==> sol:  -- Cpus:              2
==> sol:  -- Cpus:              2
 INFO interface: info:  -- Memory:            1024M
 INFO interface: info: ==> sol:  -- Memory:            1024M
==> sol:  -- Memory:            1024M
 INFO interface: info:  -- Management MAC:
 INFO interface: info: ==> sol:  -- Management MAC:
==> sol:  -- Management MAC:
 INFO interface: info:  -- Loader:
 INFO interface: info: ==> sol:  -- Loader:
==> sol:  -- Loader:
 INFO interface: info:  -- Base box:          debian/jessie64
 INFO interface: info: ==> sol:  -- Base box:          debian/jessie64
==> sol:  -- Base box:          debian/jessie64
 INFO interface: info:  -- Storage pool:      default
 INFO interface: info: ==> sol:  -- Storage pool:      default
==> sol:  -- Storage pool:      default
 INFO interface: info:  -- Image:             /var/lib/libvirt/images/HomeLab_sol.img (10G)
 INFO interface: info: ==> sol:  -- Image:             /var/lib/libvirt/images/HomeLab_sol.img (10G)
==> sol:  -- Image:             /var/lib/libvirt/images/HomeLab_sol.img (10G)
 INFO interface: info:  -- Volume Cache:      default
 INFO interface: info: ==> sol:  -- Volume Cache:      default
==> sol:  -- Volume Cache:      default
 INFO interface: info:  -- Kernel:
 INFO interface: info: ==> sol:  -- Kernel:
==> sol:  -- Kernel:
 INFO interface: info:  -- Initrd:
 INFO interface: info: ==> sol:  -- Initrd:
==> sol:  -- Initrd:
 INFO interface: info:  -- Graphics Type:     vnc
 INFO interface: info: ==> sol:  -- Graphics Type:     vnc
==> sol:  -- Graphics Type:     vnc
 INFO interface: info:  -- Graphics Port:     5900
 INFO interface: info: ==> sol:  -- Graphics Port:     5900
==> sol:  -- Graphics Port:     5900
 INFO interface: info:  -- Graphics IP:       127.0.0.1
 INFO interface: info: ==> sol:  -- Graphics IP:       127.0.0.1
==> sol:  -- Graphics IP:       127.0.0.1
 INFO interface: info:  -- Graphics Password: Not defined
 INFO interface: info: ==> sol:  -- Graphics Password: Not defined
==> sol:  -- Graphics Password: Not defined
 INFO interface: info:  -- Video Type:        cirrus
 INFO interface: info: ==> sol:  -- Video Type:        cirrus
==> sol:  -- Video Type:        cirrus
 INFO interface: info:  -- Video VRAM:        9216
 INFO interface: info: ==> sol:  -- Video VRAM:        9216
==> sol:  -- Video VRAM:        9216
 INFO interface: info:  -- Keymap:            en-us
 INFO interface: info: ==> sol:  -- Keymap:            en-us
==> sol:  -- Keymap:            en-us
 INFO interface: info:  -- TPM Path:
 INFO interface: info: ==> sol:  -- TPM Path:
==> sol:  -- TPM Path:
 INFO interface: info:  -- INPUT:             type=mouse, bus=ps2
 INFO interface: info: ==> sol:  -- INPUT:             type=mouse, bus=ps2
==> sol:  -- INPUT:             type=mouse, bus=ps2
 INFO interface: info:  -- Command line :
 INFO interface: info: ==> sol:  -- Command line :
==> sol:  -- Command line :
ERROR warden: Error occurred: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unknown procedure: 350
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unknown procedure: 350
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unknown procedure: 350
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000002c058d0>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-c518416c6a67f5125863488caa8cc9e1
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000002c6fa50>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::ProviderLibvirt::Errors::FogCreateServerError: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unknown procedure: 350>
ERROR vagrant: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unknown procedure: 350
ERROR vagrant: /home/aetherith/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/create_domain.rb:247:in `rescue in call'
/home/aetherith/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/create_domain.rb:243:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/home/aetherith/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/home/aetherith/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/handle_box_image.rb:111:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/home/aetherith/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/handle_storage_pool.rb:50:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/home/aetherith/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unknown procedure: 350
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unknown procedure: 350
 INFO interface: Machine: error-exit ["VagrantPlugins::ProviderLibvirt::Errors::FogCreateServerError", "Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unknown procedure: 350"]
```

**A Vagrantfile to reproduce the issue:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"

    config.vm.provider :libvirt do |libvirt|
        libvirt.host = "ymir.asgard.aetherith.net"
        libvirt.connect_via_ssh = true
        libvirt.username = "aetherith"
    end

    default_router = "192.168.1.1"

    # sol - Primary DNS server
    config.vm.define :sol do |sol|
        sol.vm.hostname = "sol.asgard.aetherith.net"
        sol.vm.network :public_network,
            :ip => "192.168.1.3",
            :mac => "4E:D8:BA:7D:CA:C6",
            :dev => "br0",
            :mode => "bridge",
            :type => "bridge"
        sol.vm.synced_folder ".", "/vagrant", disabled: true
        sol.vm.provider :libvirt do |domain|
            domain.autostart = true
            domain.cpus = 2
            domain.memory = 1024
        end

        # Remove default gateway.
        sol.vm.provision "shell",
            run: "always",
            inline: "ip route delete default"
        # Add a new one via the default router.
        sol.vm.provision "shell",
            run: "always",
            inline: "ip route add default via #{default_router}"
    end
    # Additional Ansible configuration.
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.vault_password_file = ".vault_password"
        ansible.playbook = "site.yml"
    end
end
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by lukas2511** [comment]
libvirt 1.2.12 introduced a new symbol "virDomainDefineXMLFlags", ruby-libvirt seems to be using that symbol if the client version supports it, but this fails on the serverside because it doesn't know that symbol.

There is a `HAVE_VIRDOMAINDEFINEXMLFLAGS` define that has to be set for the new symbol to be used, this seems to be set by default by extconf.rb.
I don't really know if there is a way to override this behaviour without removing it from the code...

**Comment by lukas2511** [comment]
My temporary solution is to just add `#define HAVE_VIRDOMAINDEFINEXMLFLAGS 0` to libvirt.h before building the native extension, this seems to be working.

**Comment by electrofelix** [comment]
Sounds like something that would be best solved in fog-libvirt, where it could check what the remote connection supports before making certain method calls

**Comment by stefancocora** [comment]
Thanks @lukas2511 , your advice from https://github.com/vagrant-libvirt/vagrant-libvirt/issues/716#issuecomment-271649007 got me passed the "unknown procedure: 350" issue.

Unfortunately it looks like vagrant might(assumption) be calling `virNetworkGetDHCPLeases` for its own management network... 
```
.vagrant.d/gems/2.2.5/gems/fog-libvirt-0.3.0/lib/fog/libvirt/requests/compute/dhcp_leases.rb:8:in `dhcp_leases': Call to virNetworkGetDHCPLeases failed: unknown procedure: 341 (Libvirt::Error)
...

PRETTY_NAME="Ubuntu 14.04.5 LTS"
...
ii  libvirt-bin                            1.2.2-0ubuntu13.1.17                       amd64        programs for the libvirt library
ii  libvirt-dev                            1.2.2-0ubuntu13.1.17                       amd64        development files for the libvirt library
ii  libvirt0                               1.2.2-0ubuntu13.1.17                       amd64        library for interfacing with different virtualization systems
```

My server(ubuntu) version of libvirt is too old, and ruby-libvirt is calling a method that libvirt on the server side doesn't know how to handle.
I've tested the same client software (vagrant + vagrant-libvirt) against the laptop's localhost `libvirtd` and it works fine:
```
System:   Kernel: 4.10.6-1-ARCH x86_64 (64 bit) ... Distro: Arch Linux

vagrant --version
Vagrant 1.9.2
...
vagrant plugin list
vagrant-libvirt (0.0.37)
...
pacman -Q|grep libvirt
libvirt 3.1.0-1
libvirt-glib 1.0.0-1
libvirt-python 3.1.0-1
```

This new issue "unknown procedure: 341 (Libvirt::Error)" looks to be related to a get DHCP lease on the `libvirtd`(ubuntu) side as seen in https://github.com/libvirt/libvirt/blob/91c3d430c96ca365ae40bf922df3e4f83295e331/src/remote_protocol-structs#L3190

**Comment by infernix** [comment]
Not sure if we can fix this in vagrant-libvirt. Is this still an issue in 1.9.7 and 0.0.40?

**Comment by moozer** [comment]
```
➜ vagrant up     
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
...
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unknown procedure: 350
```

Still a problem.
Does this mean that we cannot spin up VMs on other hosts using vagrant+libvirt?

```
➜ vagrant version
Installed Version: 2.0.0

➜ vagrant plugin list
vagrant-libvirt (0.0.40, system)
```

**Comment by moozer** [comment]
upgrading to libvirt version 3.0.0 on the remote server made it work.
sorry for the noise

**Comment by makefu** [comment]
Hey all, i am still encountering the same issue, probably because the server-side libvirt is quite ... lets call it "stable".
Is there a way to fix my client-side to avoid the issue?
